package com.phms.mapper;

import com.phms.pojo.Appointment;
import com.phms.pojo.AppointmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    long countByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int deleteByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int insert(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int insertSelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    List<Appointment> selectByExample(AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    Appointment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int updateByExample(@Param("record") Appointment record, @Param("example") AppointmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int updateByPrimaryKeySelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Mon Apr 06 17:03:33 CST 2020
     */
    int updateByPrimaryKey(Appointment record);

    List<Appointment> getAllByLimit(Appointment appointment);

    int countAllByLimit(Appointment appointment);

    List<Map<String, Object>> getFreeTimeById(@Param("id") Long id, @Param("s") String s);

    /**
     * 统计某医生在某一天、某时间段内的已预约数量（排除已取消等无效状态）
     */
    int countByDoctorAndTime(@Param("doctorId") Long doctorId,
                             @Param("appDate") String appDate,
                             @Param("timeSlot") String timeSlot);

    /**
     * 带行锁检查某医生在某一天、某时间段是否可预约
     * 使用 SELECT FOR UPDATE 锁定相关记录，防止并发超售
     * 
     * @param doctorId  医生ID
     * @param weekDay   星期几（1-7，1=周一）
     * @param appDate   预约日期（yyyy-MM-dd）
     * @param timeSlot  时间段（如 09:00-10:00）
     * @return 可预约数量（如果返回0或负数，表示不可预约）
     */
    int checkAvailableWithLock(@Param("doctorId") Long doctorId,
                               @Param("weekDay") Integer weekDay,
                               @Param("appDate") String appDate,
                               @Param("timeSlot") String timeSlot);

    /**
     * 查询即将在指定时间范围内开始的预约（用于提醒）
     * 查询状态为1（待就诊）或2（已确认）的预约
     * @param startTime 开始时间
     * @param endTime 结束时间
     * @param status 预约状态（此参数已废弃，SQL中已硬编码查询状态1和2）
     * @return 预约列表
     */
    List<Appointment> selectUpcomingAppointments(@Param("startTime") java.util.Date startTime,
                                                  @Param("endTime") java.util.Date endTime,
                                                  @Param("status") Integer status);
}